name: Build and Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Python dependencies
        run: |
          cd functions
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Deploy Firebase Functions
        uses: w9jds/firebase-action@v12.4.0
        with:
          args: deploy --only functions --project acornstoacorns
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
